import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} w-screen min-h-screen bg-neutral-100 dark:bg-neutral-900 dark:text-neutral-100 text-neutral-800`}
      >
        {children}
      </body>
    </html>
  );
}
